lib/drawtoo_web/router.ex
defmodule DrawtooWeb.Router do
  use DrawtooWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DrawtooWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DrawtooWeb do
    pipe_through :browser
    post "/games", Games.GameController, :new
    get "/games/:code", Games.GameController, :show
    get "/games/join/:code", Games.GameController, :join
    post "/games/join/:code", Games.GameController, :join_post
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", DrawtooWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: DrawtooWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/drawtoo_web/templates/page/index.html.heex
<section class="row">

  <article class="column">
    <div class="form-structor">
    <%= form_for @conn.params, Routes.game_path(@conn, :new), fn f ->  %>
	<div class="login slide-up">
		<div class="center">
			<h2 class="form-title" id="login">Create your room</h2>
			<div class="form-holder">
              <label>Player name</label>
              <%= text_input f, :user_name, placeholder: gettext "Enter your name"%>

              <label>Maximum players</label>
              <%= number_input f, :max_players, value: 4 ,placeholder: gettext "Enter Maximum players" %>

              <label>Round time</label>
              <%= number_input f, :round_time,value: 120, placeholder: gettext "Enter Round Time" %>

              <label>Number of rounds</label>
              <%= number_input f, :number_of_rounds, value: 6,  placeholder: gettext "Enter number of rounds" %>
			</div>
			<button class="submit-btn"><%= gettext "Create your room" %></button>
		</div>
	</div>
    <% end %>
</div>
   </article> 
</section>